### ISSUE TITLE
Server returned error "The other server sent messages in the wrong order. Please contact your other ..."

### ISSUE THREAD

**Issue by sagar290** [markushinz/aws-ses-pop3-server#1]
When I try to connect with Gmail its returns this error message. 
`
Error reading mail.
Server returned error "The other server sent messages in the wrong order. Please contact your other ..."
`

**Comment by markushinz** [comment]
Google refuses to accept emails if they are not presented in ascending order. I fixed this with v1.3.4 but now I am getting the `Error in RETR command: Received an empty line` message for some mails.

 Could you try again using the latest version and let me know if you experience the same issues @sagar290?

**Comment by sagar290** [comment]
Not sure, whats wrong here
`2021/05/16 12:34:24 AUTHORIZATION --> +OK
2021/05/16 12:34:24 AUTHORIZATION <-- USER career
2021/05/16 12:34:24 AUTHORIZATION --> +OK
2021/05/16 12:34:24 AUTHORIZATION <-- PASS [ *** ]
2021/05/16 12:34:24 TRANSACTION --> +OK
2021/05/16 12:34:24 TRANSACTION <-- CAPA
2021/05/16 12:34:24 TRANSACTION --> +OK
2021/05/16 12:34:24 TRANSACTION --> [ ... ]
2021/05/16 12:34:24 TRANSACTION --> .
2021/05/16 12:34:25 TRANSACTION <-- LIST
2021/05/16 12:34:25 TRANSACTION --> +OK
2021/05/16 12:34:25 TRANSACTION --> [ ... ]
2021/05/16 12:34:25 TRANSACTION --> .
2021/05/16 12:34:25 TRANSACTION <-- UIDL
2021/05/16 12:34:25 TRANSACTION --> +OK
2021/05/16 12:34:25 TRANSACTION --> [ ... ]
2021/05/16 12:34:25 TRANSACTION --> .
2021/05/16 12:34:25 TRANSACTION <-- RETR 1
2021/05/16 12:34:25 Error handler.provider.GetEmailPayload(): NoSuchKey: The specified key does not exist.`

**Comment by markushinz** [comment]
I was able to resolve all the remaining issues I had with Google Mail (https://github.com/markushinz/aws-ses-pop3-server/commit/05299ce3eb2cf457e1da19603ed94dbb3cfed7d0).

Are you using a prefix for your S3 bucket? Please try again using version 1.4.2. I tried to do some improvements in there as well. You can also enable verbose logging by setting the ENV var `POP3_VERBOSE="true"` or the respective key in the config.

**Comment by sagar290** [comment]
> I was able to resolve all the remaining issues I had with Google Mail ([05299ce](https://github.com/markushinz/aws-ses-pop3-server/commit/05299ce3eb2cf457e1da19603ed94dbb3cfed7d0)).
> 
> Are you using a prefix for your S3 bucket? Please try again using version 1.4.2. I tried to do some improvements in there as well. You can also enable verbose logging by setting the ENV var `POP3_VERBOSE="true"` or the respective key in the config

yes, it's fixed now :D
