### ISSUE TITLE
Multiple e-mail accounts on Mozilla Thunderbird

### ISSUE THREAD

**Issue by binlab** [markushinz/aws-ses-pop3-server#322]
When using the same **POP3 server** domain name e.g. `email.example.com` and one more account with a `jwt` username **Mozilla Thunderbird** (maybe, on other clients too) shows the error:

`An account with that user name and server name already exists. Please enter a different user name and/or server name.`

Currently, the **POP3 server** is [checking](https://github.com/markushinz/aws-ses-pop3-server/blob/1879caa522d3b55fe0523b0f723ab87341d5fb26/pkg/provider/provider.go#L73) if the _username_ matches the string `jwt`. Maybe we can change the validation logic a bit and look just for substring `jwt` in a _username_, for example, `user@jwt`. Or even check if the _password_ matches a valid **JWT** token (it's better I guess) and ignore the _username_ field and as a consequence allow any name to make sure of account uniqueness. 

Does it make sense, what do you think?

**Comment by markushinz** [comment]
Hi @binlab I completely removed the validation of the username field. Hope that helps :)
