### ISSUE TITLE
A message in your account user@example.com was listed with an invalid size. It has been left on the server.

### ISSUE THREAD

**Issue by sagar290** [markushinz/aws-ses-pop3-server#9]
When someone makes a cc reply to my mail. 
`A message in your account user@example.com was listed with an invalid size. It has been left on the server.`
this error is showing in my inbox. 

Note: I connect the pop3 server to a gmail account.

**Comment by markushinz** [comment]
Hi @sagar290, sorry for my late reply. Unfortunately I can't recreate your error. I also couldn't find any useful information about this error (but have you tried https://support.google.com/mail/thread/70538671/received-emails-invalid-size?hl=en ?). However, I will create a permanent setup with Gmail and update this issue as soon as I get the error myself or maybe even find a solution
